# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='deposite',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='holder',
            name='withdraw',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holder',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
