# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0004_remove_holder_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='name',
            field=models.CharField(default='vikram', max_length=20),
            preserve_default=False,
        ),
    ]
