# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0009_auto_20161117_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='lis',
            field=models.CharField(max_length=1000),
        ),
    ]
