# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0012_auto_20161119_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='name',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
