# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0019_auto_20161119_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
