# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0021_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='name',
            new_name='name1',
        ),
    ]
