# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0023_auto_20161119_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
