# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0024_auto_20161119_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
