# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0025_holder_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
