# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0027_auto_20161119_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='name1',
            new_name='employeId',
        ),
    ]
