# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0028_auto_20161120_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='identityPr',
            field=models.CharField(choices=[('DL', 'Driverlicence'), ('PP', 'PassPort')], default='DL', max_length=5),
        ),
    ]
