# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0029_number_identitypr'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='upload',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
