# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0032_remove_number_addressp'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='adressp',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
