# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0033_number_adressp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='number',
            name='identityPr',
            field=models.CharField(choices=[('Driver_Licence', 'Driverlicence'), ('Passport', 'PassPort')], default='DL', max_length=15),
        ),
        migrations.AddField(
            model_name='number1',
            name='anumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boapp.Number'),
        ),
    ]
