# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0034_auto_20161126_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
